services:
  wagtail:
    image: andrewthomaslee/wagtail2nix:latest  
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - wagtail2nix_data:/data
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - POSTGRES_ENGINE=${POSTGRES_ENGINE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wagtail2nix.entrypoints=websecure"
      - "traefik.http.routers.wagtail2nix.rule=Host(`wagtail2nix.netsam.dev`)"
      - "traefik.http.routers.wagtail2nix.service=wagtail2nix"
      - "traefik.http.routers.wagtail2nix.tls=true"
      - "traefik.http.routers.wagtail2nix.tls.options=cloudflare-mtls@file"
      - "traefik.http.services.wagtail2nix.loadbalancer.server.port=8000"
      - "traefik.http.services.wagtail2nix.loadbalancer.passhostheader=true"

  db:
    volumes:
      - wagtail2nix_postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    labels:
      - "tsdproxy.enable=true"
      - "tsdproxy.name=wagtail2nix-postgres"

volumes:
  wagtail2nix_postgres_data:
  wagtail2nix_data: