services:
  wagtail:
    image: wagtail-dev:latest  
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - wagtail_data_dev:/data

    command: uv run sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml


  db:
    ports:
      - "5432:5432"
    volumes:
      - wagtail_postgres_data_dev:/var/lib/postgresql
    env_file:
      - .env.dev

volumes:
  wagtail_postgres_data_dev:
  wagtail_data_dev: